### ISSUE TITLE
Properties are removed from attributes and data elements

### ISSUE THREAD

**Issue by teug91** [hispindia/whonet-importer#6]
All properties which are not defined are being removed (e.g. `formName` and previously `optionSet`).

See [components/settings/DataElementsTable.js](https://github.com/hispindia/whonet-importer/blob/4e97edada44d14ec416c33cd5dc335fb28a944e0/src/components/settings/DataElementsTable.js#L173). Instead of defining all the properties, perhaps we can do something like this?

```js
jsonPayload = JSON.stringify({
  ...customElementString
  code: updateArray[i].value
})
```

Or use `PATCH`? At the very least we shouldn't assume that certain properties are not used.

**Comment by Julhas08** [comment]
It has resolved for elements and attributes mapping.

**Comment by Julhas08** [comment]
It has resolved for elements and attributes mapping.

**Comment by Julhas08** [comment]
It has resolved for elements and attributes mapping.

**Comment by teug91** [comment]
Won't the `color` property, for example, be removed ? Like I said, I don't think it's a good idea to hard-code the properties. If we update to a new version of DHIS2, we would have to check if the new version has introduced new properties and add them to the app.

**Comment by Julhas08** [comment]
Ok. Thank you. Should I add the color property in this payload?

**Comment by teug91** [comment]
Does `customElementString` contain all the properties? If so, we can use the spread operator (...) like in my code bit. Same for attributes. 

```js
jsonPayload = JSON.stringify({
  ...customElementString
  code: updateArray[i].value
})
```

**Comment by Julhas08** [comment]
Yes, it contains all the properties. I've updated and tested in amr server.

**Comment by Julhas08** [comment]
Color and icon properties are working fine with this spread operator. Thank you. :)
